### PR TITLE
Cleanup, refactor and fix tests for an initial GEM release

### PR DESCRIPTION
**Pull request by geku**
The current state was not working and broken against the newest state_machines changes. As we are depending on state_machines and Mongoid integration I fixed all broken tests and on the way restructured the files according to the `state_machines-activerecord` project.
- bumped version to 0.1.0
- added simple readme
- extracted all test classes in separate files
- extracted helper methods to `test_helper`
- removed Observer support as it is no longer supported by Rails/Mongoid
- added default locales in `locale.rb`
- fixed inclusion of `state_machines-activemodel` module
- fixed tests (tests are mostly the same as before, some smaller fixes have been required and I removed a couple of tests after I didn't find them covered in `state_machines-activerecord`)

Would be happy if you can merge the changes and publish a GEM based on the new code. Or if changes are required please let me know. Thanks a lot.

### CODE REVIEW

**Comment by seuros** [comment]
This is awesome. Thank you :green_heart: :heart:

**Comment by seuros** [comment]
I will merge and do some changes. (eq : AR 3.2, 4.0 is unsupported)

**Comment by seuros** [comment]
released , could you try it ?

**Comment by geku** [comment]
Wow, awesome! The gem works for me. And the failing test is my fault, didn't catch my last minute change:

```
IntegrationTest
  test_should_have_defaults                                       FAIL (0.00s)
Minitest::Assertion:         --- expected
        +++ actual
        @@ -1 +1 @@
        -{:action=>:save}
        +{:action=>:save, :use_transactions=>false}
        /home/travis/build/state-machines/state_machines-mongoid/test/integration_test.rb:17:in `test_should_have_defaults'
```

`{:action=>:save, :use_transactions=>false}` is correct. 

Thanks a lot for your quick merge, really appreciate it!

**Pull request merged**
